//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPCWebs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Property()
        {
            this.FullContracts = new HashSet<FullContract>();
            this.InstallmentContracts = new HashSet<InstallmentContract>();
            this.PropertyServices = new HashSet<PropertyService>();
        }
    
        public int ID { get; set; }
        public string PropertyCode { get; set; }
        public string PropertyName { get; set; }
        public int PropertyTypeID { get; set; }
        public string Description { get; set; }
        public int DistrictID { get; set; }
        public string Address { get; set; }
        public Nullable<int> Area { get; set; }
        public Nullable<int> BedRoom { get; set; }
        public Nullable<int> BathRoom { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<double> InstallmentRate { get; set; }
        public string Avatar { get; set; }
        public string Album { get; set; }
        public Nullable<int> PropertyStatusID { get; set; }
    
        public virtual District District { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FullContract> FullContracts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstallmentContract> InstallmentContracts { get; set; }
        public virtual PropertyStatu PropertyStatu { get; set; }
        public virtual PropertyType PropertyType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyService> PropertyServices { get; set; }
    }
}
